mixed-port: 7890 # 混合端口，HTTP和SOCKS5用一个端口
allow-lan: true # 允许局域网的连接（共享代理）
bind-address: "*" # 监听IP白名单，可绑定单个IPv4和v6地址，"*" 为绑定所有IP地址，仅在将allow-lan设置为true时适用

ipv6: true # 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
mode: rule # 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
log-level: info # 设置日志输出级别 (5 个级别：silent / error / warning / info / debug）

external-controller: 127.0.0.1:9090 # 外部控制器监听地址，可以使用 RESTful API 来控制你的 clash 内核

dns:
  enable: true # 关闭将使用系统 DNS
  ipv6: true # IPV6解析开关；如果为false，将返回ipv6结果为空
  enhanced-mode: fake-ip # 模式：redir-host或fake-ip
  listen: 0.0.0.0:53 # DNS 监听地址
  default-nameserver: [223.5.5.5, 119.29.29.29]
  # 解析非IP的dns用的dns服务器，只支持纯IP
  nameserver: ['https://dns.alidns.com/dns-query', 'https://doh.pub/dns-query']
  # 默认DNS服务器，支持udp/tcp/dot/doh/doq

  fake-ip-range: 198.18.0.1/16 # Fake-IP 解析地址池
  fake-ip-filter: ["*.lan", "cable.auth.com", "*.msftconnecttest.com", "*.msftncsi.com", "network-test.debian.org", "detectportal.firefox.com", "resolver1.opendns.com", "*.srv.nintendo.net", "*.stun.playstation.net", "xbox.*.microsoft.com", "*.xboxlive.com", "stun.*", "global.turn.twilio.com", "global.stun.twilio.com", "localhost.*.qq.com", "localhost.*.weixin.qq.com", "*.logon.battlenet.com.cn", "*.logon.battle.net", "*.blzstatic.cn", "music.163.com", "*.music.163.com", "*.126.net", "musicapi.taihe.com", "music.taihe.com", "songsearch.kugou.com", "trackercdn.kugou.com", "*.kuwo.cn", "api-jooxtt.sanook.com", "api.joox.com", "joox.com", "y.qq.com", "*.y.qq.com", "streamoc.music.tc.qq.com", "mobileoc.music.tc.qq.com", "isure.stream.qqmusic.qq.com", "dl.stream.qqmusic.qq.com", "aqqmusic.tc.qq.com", "amobile.music.tc.qq.com", "*.xiami.com", "*.music.migu.cn", "music.migu.cn", "proxy.golang.org", "*.mcdn.bilivideo.cn", "*.cmpassport.com", "id6.me", "open.e.189.cn", "mdn.open.wo.cn", "opencloud.wostore.cn", "auth.wosms.cn", "*.jegotrip.com.cn", "*.icitymobile.mobi", "*.pingan.com.cn", "*.cmbchina.com", "pool.ntp.org", "*.pool.ntp.org", "ntp.*.com", "time.*.com", "ntp?.*.com", "time?.*.com", "time.*.gov", "time.*.edu.cn", "*.ntp.org.cn", "PDC._msDCS.*.*", "DC._msDCS.*.*", "GC._msDCS.*.*"]
  # Fake-ip 过滤，列表中的域名返回真实IP

######### 锚点 start #########

# 规则行为相关
c: &c {type: http, behavior: classical, interval: 86400, format: text}

d: &d {type: http, behavior: domain, interval: 86400, format: text}

i: &i {type: http, behavior: ipcidr, interval: 86400, format: text}

# 代理组相关
g: &g {type: select, proxies: [Proxy, Auto, Fallback, HongKong, TaiWan, Pacific, Japan, Americas, EMEA, DIRECT]}

# 远程订阅相关
p: &p {type: http, interval: 86400, benchmark-timeout: 5, health-check: {enable: true, url: 'http://www.apple.com/library/test/success.html', interval: 600}}

# 订阅引用相关
u: &u {type: select, use: [Subscribe]}

######### 锚点 end #########

# 本地服务器
proxies: null

# 远程订阅
proxy-providers:
  Subscribe: {!!merge <<: *p, path: ./proxy_providers/subscribe.yaml, url: ""}
# 1. 请使用Clash类型订阅链接填入引号""内使用,
# 2. 或可使用通用订阅链接通过Sub-Store进行订阅转换(用于Stash)。

# 代理组
proxy-groups:
# 漏网之鱼
- {name: Final, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Final.png', !!merge <<: *g, proxies: [Proxy, DIRECT],}

# 节点切换
- {name: Proxy, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Rocket.png', !!merge <<: *g, proxies: [Auto, Fallback, HongKong, TaiWan, Pacific, Japan, Americas, EMEA],}

# 自动选择
- {name: Auto, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Auto.png', type: url-test, lazy: true, !!merge <<: *u,}

# 故障转移
- {name: Fallback, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Available.png', type: fallback, !!merge <<: *u,}

# 国外网站
- {name: Global, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Global.png', !!merge <<: *g,}

# 国内网站
- {name: Mainland, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/China_Map.png', !!merge <<: *g, proxies: [DIRECT, Proxy, Auto],}

# 人工智能
- {name: AI, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Bot.png', !!merge <<: *g, proxies: [Americas, Japan, Pacific, TaiWan, EMEA],}

# 油管视频
- {name: YouTube, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/YouTube.png', !!merge <<: *g,}

# 奈飞影视
- {name: NETFLIX, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Netflix.png', !!merge <<: *g,}

# 迪士尼+
- {name: Disney+, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Disney.png', !!merge <<: *g,}

# Emby
- {name: Emby, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Emby.png', !!merge <<: *g,}

# 哔哩哔哩
- {name: BiliBili, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/bilibili_3.png', !!merge <<: *g, proxies: [DIRECT, HongKong, TaiWan],}

# 声田音乐
- {name: Spotify, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Spotify.png', !!merge <<: *g,}

# 网易云音乐
- {name: NetEaseMusic, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Netease_Music.png', !!merge <<: *g, proxies: [DIRECT],}

# 海外抖音
- {name: TikTok, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/TikTok.png', !!merge <<: *g,}

# 国际媒体
- {name: Streaming, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Streaming.png', !!merge <<: *g,}

# 电报信息
- {name: Telegram, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Telegram_X.png', !!merge <<: *g,}
# Twitter(X)
- {name: Twitter, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Twitter.png', !!merge <<: *g,}
# 苹果服务
- {name: Apple, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Apple_1.png', !!merge <<: *g, proxies: [DIRECT, Proxy, Auto, Fallback, HongKong, TaiWan, Pacific, Japan, Americas, EMEA],}

# 谷歌服务
- {name: Google, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Google_Search.png', !!merge <<: *g,}

# 微软服务
- {name: Microsoft, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Windows_11.png', !!merge <<: *g, proxies: [DIRECT, Proxy, Auto, Fallback, HongKong, TaiWan, Pacific, Japan, Americas, EMEA],}

# 游戏平台
- {name: Games, icon: 'https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Game.png', !!merge <<: *g,}

- {name: HongKong, icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/HK.png', !!merge <<: *u, filter: "港|🇭🇰|HK|(?i)Hong",}

- {name: TaiWan, icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/CN.png', !!merge <<: *u, filter: "台|🇨🇳|🇹🇼|湾|TW|(?i)Taiwan",}

- {name: Japan, icon: 'https://raw.githubusercontent.com/Orz-3/mini/master/Color/JP.png', !!merge <<: *u, filter: "日|🇯🇵|东京|JP|(?i)Japan",}

- {name: Pacific, icon: 'https://github.com/shindgewongxj/WHATSINStash/raw/main/icon/torii.png', !!merge <<: *u, filter: "SG|KR|Australia|India|Indonesia|Malaysia|Macao|Mongolia|New Zealand|North Korea|Philippines|Thailand|Vietnam",}

- {name: Americas, icon: 'https://github.com/shindgewongxj/WHATSINStash/raw/main/icon/christtheredeemer.png', !!merge <<: *u, filter: "美|🇺🇲|US|CA[0-9].*|Mexico|Brazil|Argentina|Chile|Colombia|Peru",}

- {name: EMEA, icon: 'https://github.com/shindgewongxj/WHATSINStash/raw/main/icon/leaningtowerofpisa.png', !!merge <<: *u, filter: "DE|UK|FR|Austria|Belgium|Bulgaria|Czech|Denmark|Dubai|Egypt|España|Finland|Greece|Hungary|Iceland|Ireland|Israel|Italia|Kazakhstan|Luxembourg|Moldova|Nigeria|Netherlands|Norway|Pakistan|Poland|Portugal|Romania|Russia|South Africa|Sweden|Switzerland|Türkiye|Ukraine|Uzbekistan|Antarctica",}

# 远程规则集
rule-providers:
  # 隐私网络
  private-domain: {!!merge <<: *d, path: ./ruleset/private-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.list'}

  private-ip: {!!merge <<: *i, path: ./ruleset/private-ip.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.list'}

  # 人工智能
  openai-classical: {!!merge <<: *c, path: ./ruleset/openai-classical.list, url: 'https://raw.gitmirror.com/Coldvvater/Mononoke/master/Stash/RuleSet/AI.list'}


  # 油管视频
  youtube-domain: {!!merge <<: *d, path: ./ruleset/youtube-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.list'}

  # 奈飞影视
  netflix-domain: {!!merge <<: *d, path: ./ruleset/netflix-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.list'}

  netflix-ip: {!!merge <<: *i, path: ./ruleset/netflix-ip.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.list'}

  # 迪士尼+
  disney-domain: {!!merge <<: *d, path: ./ruleset/disney-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.list'}

  # Emby
  emby-classical: {!!merge <<: *c, path: ./ruleset/emby-classical.list, url: 'https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.list'}

  # 动画疯
  bahamut-domain: {!!merge <<: *d, path: ./ruleset/bahamut-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.list'}

  # 哔哩哔哩东南亚
  biliintl-domain: {!!merge <<: *d, path: ./ruleset/biliintl-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/biliintl.list'}

  # 哔哩哔哩
  bilibili-domain: {!!merge <<: *d, path: ./ruleset/bilibili-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.list'}

  bilibili-ip: {!!merge <<: *i, path: ./ruleset/bilibili-ip.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/bilibili.list'}

  # 声田音乐
  spotify-domain: {!!merge <<: *d, path: ./ruleset/spotify-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.list'}

  # 网易云音乐
  neteasemusic-classical: {!!merge <<: *c, path: ./ruleset/neteasemusic-classical.list, url: 'https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.list'}

  # 海外抖音
  tiktok-domain: {!!merge <<: *d, path: ./ruleset/tiktok-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.list'}

  # 国际媒体
  streamingmedia-classical: {!!merge <<: *c, path: ./ruleset/streamingmedia-classical.list, url: 'https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list'}

  # 电报信息
  telegram-domain: {!!merge <<: *d, path: ./ruleset/telegram-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.list'}

  telegram-ip: {!!merge <<: *i, path: ./ruleset/telegram-ip.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.list'}

  # GitHub
  github-domain: {!!merge <<: *d, path: ./ruleset/github-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.list'}

  # Twitter
  twitter-domain: {!!merge <<: *d, path: ./ruleset/twitter-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.list'}

  twitter-ip: {!!merge <<: *i, path: ./ruleset/twitter-ip.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.list'}

  # 苹果代理服务
  apple-classical: {!!merge <<: *c, path: ./ruleset/apple-domain.list, url: 'https://raw.gitmirror.com/Coldvvater/Mononoke/master/Stash/RuleSet/AppleProxyService.list'}

  # 苹果服务
  apple-domain: {!!merge <<: *d, path: ./ruleset/apple-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.list'}

  apple-ip: {!!merge <<: *i, path: ./ruleset/apple-ip.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.list'}

  # 谷歌服务
  google-domain: {!!merge <<: *d, path: ./ruleset/google-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.list'}

  google-ip: {!!merge <<: *i, path: ./ruleset/google-ip.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.list'}

  # 微软服务
  microsoft-domain: {!!merge <<: *d, path: ./ruleset/microsoft-domain.list, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.list'}

  # 游戏平台
  games-classical: {!!merge <<: *c, path: ./ruleset/games-classical.list, url: 'https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.list'}

  # 国内网站
  cn-domain: {!!merge <<: *d, path: ./ruleset/cn-domain.yaml, url: 'https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geosite/cn.list'}

  # 国外网站
  proxy-domain: {!!merge <<: *d, path: ./ruleset/proxy-domain.yaml, url: 'https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy.list'}

# 分流规则引用
rules:
#  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT
#  - SCRIPT,quic,REJECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.metacubex.one,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN,d.metacubex.one,DIRECT
- DOMAIN,raw.gitmirror.com,Proxy

- RULE-SET,private-domain,DIRECT
- RULE-SET,openai-classical,AI
- RULE-SET,youtube-domain,YouTube
- RULE-SET,netflix-domain,NETFLIX
- RULE-SET,disney-domain,Disney+
- RULE-SET,emby-classical,Emby
- RULE-SET,bahamut-domain,TaiWan
- RULE-SET,biliintl-domain,Streaming
- RULE-SET,bilibili-domain,BiliBili
- RULE-SET,spotify-domain,Spotify
- RULE-SET,neteasemusic-classical,NetEaseMusic
- RULE-SET,tiktok-domain,TikTok
- RULE-SET,streamingmedia-classical,Streaming
- RULE-SET,telegram-domain,Telegram
- RULE-SET,github-domain,Global
- RULE-SET,twitter-domain,Twitter
- RULE-SET,apple-classical,Global
- RULE-SET,apple-domain,Apple
- RULE-SET,google-domain,Google
- RULE-SET,microsoft-domain,Microsoft
- RULE-SET,games-classical,Games
- RULE-SET,proxy-domain,Global

- RULE-SET,google-ip,Google
- RULE-SET,netflix-ip,NETFLIX
- RULE-SET,telegram-ip,Telegram
- RULE-SET,twitter-ip,Twitter
- RULE-SET,cn-domain,Mainland
- RULE-SET,bilibili-ip,BiliBili
- RULE-SET,apple-ip,Apple
- RULE-SET,private-ip,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Final

script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
